project_id = "kcyifzayxgsogdkxmykm"

[functions.reflect]
verify_jwt = false

[functions.insights]
verify_jwt = false

[functions.explore-theme]
verify_jwt = false

[functions.loops]
verify_jwt = false