project_id = "kcyifzayxgsogdkxmykm"

[functions.reflect]
verify_jwt = true

[functions.insights]
verify_jwt = true

[functions.explore-theme]
verify_jwt = true

[functions.loops]
verify_jwt = true

[functions.resend]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.reengagement-nudge]
verify_jwt = false
